package com.manikas.redgen.entity.aigenerator;

//Enum for possible placeable blocks

public enum BlockSet {
    GREEN_WOOL,
    GLASS,
    SLAB,
    PISTON,
    STICKY_PISTON,
    SLIME_BLOCK,
    REDSTONE_DUST,
    REDSTONE_BLOCK,
    REDSTONE_TORCH,
    OBSERVER,
    REDSTONE_REPEATER_1,
    REDSTONE_REPEATER_2,
    REDSTONE_REPEATER_3,
    REDSTONE_REPEATER_4,
    REDSTONE_COMPARATOR_SUBTRACT,
    REDSTONE_COMPARATOR_COMPARE,
    REDSTONE_LAMP,
    HOPPER,
    DISPENSER,
    DROPPER,
    BARREL,
    TARGET,
    STONE_BUTTON,
    OAK_BUTTON,
    LEVER,
    NULL
}
